// <auto-generated />
using System;
using Beagl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Beagl.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260410142226_SeedBreeds")]
    partial class SeedBreeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Beagl.Infrastructure.Breeds.Entities.BreedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AnimalType")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionFr")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Breeds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Friendly, outgoing, and high-spirited companion.",
                            DescriptionFr = "Compagnon amical, sociable et plein d'entrain.",
                            IsActive = true,
                            NameEn = "Labrador Retriever",
                            NameFr = "Labrador"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Intelligent, loyal, and versatile working dog.",
                            DescriptionFr = "Chien de travail intelligent, loyal et polyvalent.",
                            IsActive = true,
                            NameEn = "German Shepherd",
                            NameFr = "Berger allemand"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Gentle, reliable family dog with a love for water.",
                            DescriptionFr = "Chien de famille doux et fiable qui adore l'eau.",
                            IsActive = true,
                            NameEn = "Golden Retriever",
                            NameFr = "Golden Retriever"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Adaptable, playful, and alert small companion.",
                            DescriptionFr = "Petit compagnon adaptable, joueur et alerte.",
                            IsActive = true,
                            NameEn = "French Bulldog",
                            NameFr = "Bouledogue français"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Calm, courageous, and friendly breed.",
                            DescriptionFr = "Race calme, courageuse et amicale.",
                            IsActive = true,
                            NameEn = "Bulldog",
                            NameFr = "Bouledogue anglais"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Highly intelligent and elegant breed in multiple sizes.",
                            DescriptionFr = "Race très intelligente et élégante disponible en plusieurs tailles.",
                            IsActive = true,
                            NameEn = "Poodle",
                            NameFr = "Caniche"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Merry, curious hound with an excellent nose.",
                            DescriptionFr = "Chien courant joyeux et curieux au flair excellent.",
                            IsActive = true,
                            NameEn = "Beagle",
                            NameFr = "Beagle"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Confident, powerful guardian and loyal companion.",
                            DescriptionFr = "Gardien confiant et puissant, compagnon loyal.",
                            IsActive = true,
                            NameEn = "Rottweiler",
                            NameFr = "Rottweiler"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Bold, lively little dog with a big personality.",
                            DescriptionFr = "Petit chien audacieux et vif à forte personnalité.",
                            IsActive = true,
                            NameEn = "Dachshund",
                            NameFr = "Teckel"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Feisty, affectionate toy breed with a silky coat.",
                            DescriptionFr = "Race miniature fougueuse et affectueuse au pelage soyeux.",
                            IsActive = true,
                            NameEn = "Yorkshire Terrier",
                            NameFr = "Yorkshire Terrier"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Fun-loving, active, and bright family guardian.",
                            DescriptionFr = "Gardien familial actif, enjoué et intelligent.",
                            IsActive = true,
                            NameEn = "Boxer",
                            NameFr = "Boxer"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Energetic sled dog bred for endurance.",
                            DescriptionFr = "Chien de traîneau énergique élevé pour l'endurance.",
                            IsActive = true,
                            NameEn = "Siberian Husky",
                            NameFr = "Husky sibérien"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Gentle giant known for its regal appearance.",
                            DescriptionFr = "Géant doux connu pour son allure majestueuse.",
                            IsActive = true,
                            NameEn = "Great Dane",
                            NameFr = "Dogue allemand"
                        },
                        new
                        {
                            Id = new Guid("0000000e-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Sleek, powerful, and fearless protector.",
                            DescriptionFr = "Protecteur élégant, puissant et intrépide.",
                            IsActive = true,
                            NameEn = "Doberman Pinscher",
                            NameFr = "Doberman"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Affectionate lap dog with a luxurious coat.",
                            DescriptionFr = "Chien de compagnie affectueux au pelage luxueux.",
                            IsActive = true,
                            NameEn = "Shih Tzu",
                            NameFr = "Shih Tzu"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Exceptionally smart and agile herding dog.",
                            DescriptionFr = "Chien de berger exceptionnellement intelligent et agile.",
                            IsActive = true,
                            NameEn = "Border Collie",
                            NameFr = "Border Collie"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Tiny, bold, and charming companion.",
                            DescriptionFr = "Compagnon minuscule, audacieux et charmant.",
                            IsActive = true,
                            NameEn = "Chihuahua",
                            NameFr = "Chihuahua"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Lively, inquisitive toy breed with a fluffy coat.",
                            DescriptionFr = "Race miniature vive et curieuse au pelage duveteux.",
                            IsActive = true,
                            NameEn = "Pomeranian",
                            NameFr = "Poméranien"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Good-natured working dog from the Swiss Alps.",
                            DescriptionFr = "Chien de travail au bon tempérament originaire des Alpes suisses.",
                            IsActive = true,
                            NameEn = "Bernese Mountain Dog",
                            NameFr = "Bouvier bernois"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000000"),
                            AnimalType = 2,
                            DescriptionEn = "Smart, work-oriented herder with striking coat.",
                            DescriptionFr = "Berger intelligent et travailleur au pelage remarquable.",
                            IsActive = true,
                            NameEn = "Australian Shepherd",
                            NameFr = "Berger australien"
                        },
                        new
                        {
                            Id = new Guid("00000015-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Most common cat worldwide, diverse in appearance.",
                            DescriptionFr = "Chat le plus répandu au monde, à l'apparence variée.",
                            IsActive = true,
                            NameEn = "Domestic Shorthair",
                            NameFr = "Chat à poil court"
                        },
                        new
                        {
                            Id = new Guid("00000016-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Quiet, gentle cat with a long flowing coat.",
                            DescriptionFr = "Chat calme et doux au long pelage fluide.",
                            IsActive = true,
                            NameEn = "Persian",
                            NameFr = "Persan"
                        },
                        new
                        {
                            Id = new Guid("00000017-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Large, sociable cat with tufted ears.",
                            DescriptionFr = "Grand chat sociable aux oreilles touffues.",
                            IsActive = true,
                            NameEn = "Maine Coon",
                            NameFr = "Maine Coon"
                        },
                        new
                        {
                            Id = new Guid("00000018-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Vocal, social cat with striking blue eyes.",
                            DescriptionFr = "Chat vocal et sociable aux yeux bleus saisissants.",
                            IsActive = true,
                            NameEn = "Siamese",
                            NameFr = "Siamois"
                        },
                        new
                        {
                            Id = new Guid("00000019-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Docile, large cat that goes limp when held.",
                            DescriptionFr = "Grand chat docile qui se détend quand on le prend.",
                            IsActive = true,
                            NameEn = "Ragdoll",
                            NameFr = "Ragdoll"
                        },
                        new
                        {
                            Id = new Guid("0000001a-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Athletic, spotted cat with a wild appearance.",
                            DescriptionFr = "Chat athlétique et tacheté à l'allure sauvage.",
                            IsActive = true,
                            NameEn = "Bengal",
                            NameFr = "Bengal"
                        },
                        new
                        {
                            Id = new Guid("0000001b-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Easy-going, round-faced companion.",
                            DescriptionFr = "Compagnon facile à vivre au visage rond.",
                            IsActive = true,
                            NameEn = "British Shorthair",
                            NameFr = "British Shorthair"
                        },
                        new
                        {
                            Id = new Guid("0000001c-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Active, playful cat with a ticked coat.",
                            DescriptionFr = "Chat actif et joueur au pelage tiqueté.",
                            IsActive = true,
                            NameEn = "Abyssinian",
                            NameFr = "Abyssin"
                        },
                        new
                        {
                            Id = new Guid("0000001d-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Sweet-tempered cat with distinctive folded ears.",
                            DescriptionFr = "Chat au tempérament doux aux oreilles repliées distinctives.",
                            IsActive = true,
                            NameEn = "Scottish Fold",
                            NameFr = "Scottish Fold"
                        },
                        new
                        {
                            Id = new Guid("0000001e-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Hairless, energetic, and affectionate breed.",
                            DescriptionFr = "Race sans poil, énergique et affectueuse.",
                            IsActive = true,
                            NameEn = "Sphynx",
                            NameFr = "Sphynx"
                        },
                        new
                        {
                            Id = new Guid("0000001f-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Shy, gentle cat with a plush blue-grey coat.",
                            DescriptionFr = "Chat timide et doux au pelage peluché bleu-gris.",
                            IsActive = true,
                            NameEn = "Russian Blue",
                            NameFr = "Bleu russe"
                        },
                        new
                        {
                            Id = new Guid("00000020-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Hardy, large cat built for cold climates.",
                            DescriptionFr = "Grand chat robuste adapté aux climats froids.",
                            IsActive = true,
                            NameEn = "Norwegian Forest Cat",
                            NameFr = "Chat des forêts norvégiennes"
                        },
                        new
                        {
                            Id = new Guid("00000021-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Gentle, quiet cat with sapphire eyes.",
                            DescriptionFr = "Chat doux et calme aux yeux saphir.",
                            IsActive = true,
                            NameEn = "Birman",
                            NameFr = "Sacré de Birmanie"
                        },
                        new
                        {
                            Id = new Guid("00000022-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Mischievous, curly-coated cat with large ears.",
                            DescriptionFr = "Chat espiègle au pelage bouclé et aux grandes oreilles.",
                            IsActive = true,
                            NameEn = "Devon Rex",
                            NameFr = "Devon Rex"
                        },
                        new
                        {
                            Id = new Guid("00000023-0000-0000-0000-000000000000"),
                            AnimalType = 1,
                            DescriptionEn = "Persian-type cat with a short, easy-care coat.",
                            DescriptionFr = "Chat de type persan au pelage court et facile d'entretien.",
                            IsActive = true,
                            NameEn = "Exotic Shorthair",
                            NameFr = "Exotic Shorthair"
                        });
                });

            modelBuilder.Entity("Beagl.Infrastructure.EmailProviders.Entities.EmailProviderConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("EmailProviderConfigurations", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.Users.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.Users.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("RecoveryCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("\"NormalizedEmail\" IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.Users.Entities.CitizenProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommunicationPreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("LanguagePreference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CitizenProfiles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Beagl.Infrastructure.Users.Entities.CitizenProfileEntity", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("Beagl.Infrastructure.Users.Entities.CitizenProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Beagl.Infrastructure.Database.AddressEntity", "Address", b1 =>
                        {
                            b1.Property<Guid>("CitizenProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("CitizenProfileEntityId");

                            b1.ToTable("CitizenProfiles");

                            b1.WithOwner()
                                .HasForeignKey("CitizenProfileEntityId");
                        });

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Beagl.Infrastructure.Users.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
