// <auto-generated />

using System.Diagnostics.CodeAnalysis;

namespace Beagl.Infrastructure.Migrations;

[ExcludeFromCodeCoverage]
sealed partial class ApplicationDbContextModelSnapshot
{
}

// Add one partial class per migration to exclude generated migration code from coverage.
// Example for existing migration:
[ExcludeFromCodeCoverage]
partial class CreateIdentityTables
{
}

[ExcludeFromCodeCoverage]
partial class AddEmailProviderConfig
{
}
