// <auto-generated />

using System.Diagnostics.CodeAnalysis;

namespace Beagl.Infrastructure.Migrations;

[ExcludeFromCodeCoverage]
sealed partial class ApplicationDbContextModelSnapshot
{
}

// Add one partial class per migration to exclude generated migration code from coverage.
// Example for existing migration:
[ExcludeFromCodeCoverage]
partial class CreateIdentityTables
{
}

[ExcludeFromCodeCoverage]
partial class AddEmailProviderConfig
{
}

[ExcludeFromCodeCoverage]
partial class AddCitizenProfiles
{
}

[ExcludeFromCodeCoverage]
partial class EnforceUniqueEmail
{
}

[ExcludeFromCodeCoverage]
partial class AddCitizenProfileFields
{
}

[ExcludeFromCodeCoverage]
partial class ReplaceAddressWithStructuredFields
{
}

[ExcludeFromCodeCoverage]
partial class AddRecoveryCodeToUsers
{
}

[ExcludeFromCodeCoverage]
partial class AddMustChangePasswordToUsers
{
}

[ExcludeFromCodeCoverage]
partial class AddBreeds
{
}

[ExcludeFromCodeCoverage]
partial class SeedBreeds
{
}

[ExcludeFromCodeCoverage]
partial class AddColors
{
}

[ExcludeFromCodeCoverage]
partial class RemoveBreedDescription
{
}
